# Generated by Django 5.1.2 on 2024-10-31 16:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('my_app', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Artist',
            new_name='Musician',
        ),
    ]
