# Generated by Django 5.1.2 on 2024-10-31 17:18

import my_app.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_app', '0002_rename_artist_musician'),
    ]

    operations = [
        migrations.AddField(
            model_name='group',
            name='sample',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='musician',
            name='avatar',
            field=models.ImageField(blank=True, null=True, upload_to=my_app.models.musician_avatar_directory_path),
        ),
        migrations.AddField(
            model_name='musician',
            name='sample',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='musician',
            name='experience',
            field=models.CharField(max_length=100),
        ),
    ]
