# Generated by Django 5.1.2 on 2024-11-05 17:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('my_app', '0004_alter_musician_avatar'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Group',
            new_name='Band',
        ),
    ]
